version: 2.1 # use CircleCI 2.0
commands: # a collection of steps
  run_tests:
    description: "All steps for running specs from appraisal"
    parameters:
      ruby_version:
        type: string
        default: "2"
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      - restore_cache:
          keys:
            - nocms-blocks-bundle-v<< parameters.ruby_version>>-{{ checksum "Gemfile.lock" }}-{{ checksum "gemfiles/rails_4_0_mysql.gemfile.lock" }}
            - nocms-blocks-bundle-v<< parameters.ruby_version>>-

      - run: # Install Ruby dependencies
          name: Bundle Install
          command: bundle check || bundle install

      - run:
          name: Appraisal Install
          command: bundle exec appraisal install

      # Store bundle cache for Ruby dependencies
      - save_cache:
          key: nocms-blocks-bundle-v<< parameters.ruby_version>>-{{ checksum "Gemfile.lock" }}-{{ checksum "gemfiles/rails_4_0_mysql.gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Create DB
          command: bundle exec appraisal rake db:create

      - run:
          name: Run Migrations
          command: bundle exec appraisal rake db:migrate

      - run:
          name: Run specs
          command: bundle exec appraisal rspec

jobs:
  build_2_3: # runs not using Workflows must have a `build` job as entry point
    parallelism: 1 # run three instances of this job in parallel
    docker: # run the steps with Docker
      - image: circleci/ruby:2.3-jessie # ...with this image as the primary container; this is where all `steps` will run
        environment: # environment variables for primary container
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
      - image: circleci/postgres:latest-ram # database image
        environment: # environment variables for database
          POSTGRES_USER: postgres
          POSTGRES_DB: nocms_blocks_test
          POSTGRES_PASSWORD: postgres
      - image: circleci/mysql:latest-ram # database image
        command: [--default-authentication-plugin=mysql_native_password]
        environment: # environment variables for database
          MYSQL_USER: root
          MYSQL_DATABASE: nocms_blocks_test
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_HOST: '%'
    steps:
      - run_tests:
          ruby_version: '2.3.0'

  build_2_5: # runs not using Workflows must have a `build` job as entry point
    parallelism: 1 # run three instances of this job in parallel
    docker: # run the steps with Docker
      - image: circleci/ruby:2.5-jessie # ...with this image as the primary container; this is where all `steps` will run
        environment: # environment variables for primary container
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
      - image: circleci/postgres:latest-ram # database image
        environment: # environment variables for database
          POSTGRES_USER: postgres
          POSTGRES_DB: nocms_blocks_test
          POSTGRES_PASSWORD: postgres
      - image: circleci/mysql:latest-ram # database image
        command: [--default-authentication-plugin=mysql_native_password]
        environment: # environment variables for database
          MYSQL_USER: root
          MYSQL_DATABASE: nocms_blocks_test
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_HOST: '%'
    steps:
      - run_tests:
          ruby_version: '2.5.0'

workflows:
  version: 2
  build:
    jobs:
      - build_2_3
      - build_2_5


